---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import vpc variables
      include_vars: vars/output_vars

    - name: import vprofile setup variables
      include_vars: vars/vprostacksetup

    - name: create vprofile-key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: save private key to bastion-key.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey-vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: create security group for load balancer
      ec2_group:
        name: vproELB-sg
        description: allow port 80 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rule:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: create security group for vprofile stack
      ec2_group:
        name: vproStack-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rule: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELBSG_out.group.id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      regiater: vproStackSG_out

    - name: update security group with its own sg id
      ec2_group:
        name: vproStack-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{vproStackSG_out.group_id}}"